name: mycall
description: "Mycall - Communication App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  agora_rtc_engine: ^6.3.0
  flutter_contacts: ^1.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
